export const TERMS = {
  traveler: "Traveler",
  follower: "Follower",
  mission: "Mission",
  missions: "Missions",
  journal: "Journal",
  story: "Story",
  checkIn: "Check In",
  routeVote: "Route Vote",
  votes: "Votes",
  winningOption: "Winning Option",
  funds: "Funds",
  travelFunds: "Travel Funds",
  transactions: "Transactions",
  state: "State",
  travelerState: "Traveler State",
  autoState: "Auto State",
  autoEstimated: "AUTO EST.",
  pin: "Pin",
  trailLine: "Trail Line",
  options: "Options",
  manageFollowers: "Manage Followers",
  debugLog: "Debug Log",
  dangerZone: "Danger Zone",
  emergencyReset: "Emergency Reset",
  badges: "Badges",
} as const;

export const LABELS = {
  dock: {
    journal: TERMS.journal,
    missions: TERMS.missions,
    votes: TERMS.votes,
    funds: TERMS.funds,
  },
  sheets: {
    journalTitle: TERMS.journal,
    missionsTitle: TERMS.missions,
    routeVotesTitle: TERMS.votes,
    travelFundsTitle: TERMS.travelFunds,
    stateTitle: TERMS.travelerState,
    optionsTitle: TERMS.options,
  },
} as const;
